language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  on:
    tags: true
    repo: Eyevinn/fmp4-js
  api_key:
    secure: S6Q4+b9puxEKlSDFEQcLBwWAzkT6PxrYhhvlW4mk+TLWd4OiSivWZmbllNgAM5GzdGqPkoceHl1RtSR5WHRfmzITl9yuygoD+v0VDg5vSYNX4jpOHOFt2F4olzWFUlHCFA3SC0OZnzc2shaeHck2RfcNcmFyKhPbDWewIsV4lelWqyVMfcjQQOKyOpdB26BH4EU3hygWtXhewwbpfY2vO8rnqiJd7zriymQROsvA1bK78Eoxw1Kl8L7vsGnMOmnVjgTvdhobkMgJTYIj7aBle1wMuLMB+Dy23XktjLNC2yqF9Mha9Ij7We0xHLWHP9hQKtaf3GBEdLO/GF4wzzH+ltpyUJEmD9fyrzoObLMXInYjayppIIX4dvQw/diau1btToeyIhPHLh/7XlBwJ9ARFQWf4yGW+28eHNUFZ9lZyxBcE750RJLcFX53opvlh3jJhBKzNKIf6IAmzp02ov5UmaAuxLSoiKHO+u0ZHymscb9MoBjb0MMiI6jTETP6whQ6qAox5XwMztHRBIj4FirTbHRpGevuOdSzaWB0I0X1uFMCPKj4XA8Qk6iVTzB+BO3Zp8Kv2oxuTKlG/LPcCcFqL7ocS91MlRuidBGrRNyXWH265p5QqHU7ximcYUtriB7MvPBczj2ZG8j5zVkqN2AQN8ULxYYzoecQ0zo/vhQ0+nI=
