dist: trusty
language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: AK4c4pnIwoiNJhj7/rhSE9sU5fdIBy89xTmDKAuPawZGHfyon6rS31ErweEtS5fFmV05Xe+C2XmZYdGKX5MYpV9RcFZtYfmPkg6Axep2yeIpFskv2vg+eD8HHSuVXt3lN4+GIVa646ZbYLnovTrp7pa8IsSpDJZXHxtl/Ux071KON7bv/04HuQVUNO5G/WokBQmnhW55zLtNDvWuAm+mLiz2ZnqQxnnPZGUgdbI3PXZa1mTJQKOXLHDZ7iJ1D8G8nMxOUrfxM3nVBDDfB8BG0xvacStYfrXhUBL9pxrZqOJxU/1IaYf6q+Wwt5rzcPCDAEa4/ti5cDSDiEUdnVtmuOuSwJsL7UGnBs1mjboicV0mCVNnu87La+ezJfc8/irS4zJ2plieqZvQuslubMO8k8UJY9Pl950ZN5taxkDrZD2BcDBjuoVKATr1veWbepTko0FUfBONEn9mb0C2m31WZ4vrTDIo+Qb2tijTMJLWMKdcyVJq0OXmHSiABOXnuTlpKIyyHFojC2gIP6FAPhiH7fLX1vzR1xUea4pJK9wHSoGFCSsUZEvuY/431nD3qIDvs9iAYkuKM22p7GNyl5uFWeS8ZMmW0UIcqFxBzvgm7sh9GEOKHlmhFz6KJsQ9rGD1QC3rebgkvsAEnj7FLis7VIW9btQd7Z/45essZI3aO94=
  on:
    tags: true
    repo: Eyevinn/fmp4-js
