dist: trusty
language: node_js
node_js:
- 8
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: waleH42/vnNby7JzBQMwhrpheN6Z8RCtIOO0T0WbpZ5qVjc8VhAXMt1/fdSJCIHSg31Si9aDmbX3T5igKna2lkBQUf8BrtOe7KT4VdnxzNkX/eLNv6SLXzoLWc5kHT/DeRfK9zn1ddkb6cinrDKYyVxU8IFxsZqC7S/3eERqur1d9GnBQVU5zgLtu/SWAaN5d9uypxHY/seFwi/fR6KOtrTzVgnC0lEV0vH8afET4N437zwQRIhzlGxmIbv6pBDnigNgtELCuaRF/QuCG1DoLYZUFHjBrj/y9i1qeBbm/HA8jhCMxA0+RdYqQQjszZZ0+FKeAgVw0tNNTAdb9LKUyQi1HWxlSv/lR0CUIEPqXocOsx/+ZAFQEGelWL02lPvN7zeb/aR7B1FBDA0kDXJq0KAJhjTO7d6W5oozvVxIUNLeifkVO6/4PvmrYTpHRF2K32ZL/6jhbdemr2iVtfMghJ+y+o+56lQPzEhv5r/wx92ge2zb+ctAFj2f5ye9pJARH3fDx2lBYSegBofnE9NdzaQgIs6bQIgH5aphvxM7J5KRKT+9whboxtNd3nCLUXEXqhC/ddldFNZchE7i7LWs+7fnmcAxkkj4WWnb3KZyF93dWB4xikgiwIwUCqEufWHGoytiLsaa4xH5R5DGkRnQus3bJ8xgYidlq6ZKiJ7fACE=
  on:
    tags: true
    repo: Eyevinn/fmp4-js
