language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  on:
    tags: true
    repo: Eyevinn/fmp4-js
  api_key:
    secure: buFoRDUbqOpC2+OxVkFNPjDviLYmm/PxfBXroxyYj4GfslLjy/AduA59TYs0uan8pMv3XkK9d7Uc8XwqnlcCEJOYFg2Pkw+NEImfFbAIx019VbEkDPi64JeR5wORpJ/G3BErtHHWrgvIBAze8kGNvNVJCSvTiulQO1FGSxGbjQL/X8g0l5OxWvy/ea4Wt8UDy613TOkHrDMjoY9x/IPfPrEB4/KUTW3uqJvny1oO9FKMKT3y91pjOdw2sf0Z/feXBC0euv9c3vG87EWc9OpbSYODWu2Yg2MMTbyo7LNwB5DQFjftb2T6dPEs2YSDP4E75DWvKbjZyC9P8Drtru1Jn3Ya4vloGgarda25UgLXUjw0LbX+0ldA2Fbo9G1N0prH8BKFJuvwnhWN4Zp6OkAbZoN3KEx9BGbqKhT+lE6o6mZhQyJHPkZgKQKR6Mh6lyW1LcVFtUenUxvqAyq65wTeav/lYRah/AzFYlrEzD6p2A5+mOVS3yR2VA4shs0crvBmyawQfk0fnx2yDhesnSOVu5zHoclGE0ZpyU0P6360Pbn/cpEr/oqkbnAdjMvbspR6EkKcxZFp6heh9uY/RkMxZvIi8ScgEkywtusnN0q+EE+BUrCU4fZkbIcCf+2lxHAxtYZ2FEeNNFwOITZ3ag/93Mav7/KKJ5Ji5D8bPfa3iwI=
