dist: trusty
language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: l3eMR/6megnv1rh9LcV/JM0+Es4iVz0LrBR6ydnGJcbqw8nfLVvlCLlfiqsDjKl5X0dxC7xD+L0UeTkP4DAUF9mmsPo0xrsb2RUz3GouiBVAyXJpKJAxcbz6Bde1W4OSCzX0r7+YFfqf5rY/cy72O11VSPoV6ncQFQvW1ZmgkNL0n3zmYJhRd7uRJaflnyhqIasEt4+Ajmc1SlgjMRTq3AHhNLnG0F42scnjLASsoHO+oa/bYKqUhLOtIKaG+4b7cgZpBR/yOIJP5xs76geBQVTPnLCILijuRiUWcnFvdJosESvBz+jnqmPNjYVVTfwD+K8sIu18avHoZd8QiEcEDZj9mtSt7daG3sXh6jsBkQjGJU4JJpj1DEjEYQ6D5cOXlhHioUyyYkEoTtxnVqaNbPGnfeJULKPJc/Ve4Wt6tMsUPgscsFzKjMYiV2pX/QwVcQ1UgKNC8brZR9Yg9gERXfX6iDFKZL0WZHxL2Ur6cJlNYCPciZ9BNpEdOkbNTcb4a4qiFsKgHRGv8Y56NArLgjjGqbEtX0x4gySfN1XHeO/qOT1OSdxqx3LthNa4uASwlTvWRZw8a8uxOS2u8SxU4FHcQMBnHC0VK7z04OmkDojjYtdlVa/SW0EPNReRDoKTQqOAipP92cerVtgeL8EyC9iigFmtmUBpKTJzckN4p6M=
  on:
    tags: true
    repo: Eyevinn/fmp4-js
